version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/InsecureBankv2" # La ruta donde está el archivo build.gradle
    schedule:
      interval: weekly
      time: "12:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "12:00"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
